version: "3.8"
services:
    mysql:
        image: mysql:8
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "!Cyberbob03"
        command: --skip-grant-tables --skip-networking
        ports:
            - "3307:3306"
        networks:
            - my_network
        restart: always

networks:
    my_network:
        driver: bridge
