version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "!Cyberbob03"
            MYSQL_ROOT_HOST: "%"
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password # Setzt das Authentifizierungsplugin auf mysql_native_password
        volumes:
            - "E:/web/my/tmp/mysql_data:/var/lib/mysql"

volumes:
    mysql_data:
