<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function chatGptApi(){
        //phpinfo();
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
       $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"model\": \"gpt-3.5-turbo\", \"prompt\": \"Say this is a test\", \"temperature\": 0, \"max_tokens\": 7}");

        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER , false);
        $headers = array();
        $headers[] = 'Content-Type: application/json';
        
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        
        dump($result);
        
    }
}
